---
# flobal user config:
user: l3d
users:
  l3d:
    - l3d
admins:
  - l3d


# i3wm config:

i3_packages_extra:
  - ranger
  - light
  - pass

i3_keybindings_extra:
  - keybinding:
    name: Volume (mute/unmute)
    key: $mod+F12
    exec: --no-startup-id pulsemixer --toggle-mute
  - keybinding:
    name: Volue (default)
    key: $mod+Shift+F12
    exec: --no-startup-id pulsemixer --set-volume 42
  - keybinding:
    name: volume-up
    key: XF86AudioRaiseVolume
    exec: --no-startup-id pulsemixer --change-volume +4
  - keybinding:
    name: volume-down
    key: XF86AudioLowerVolume
    exec: --no-startup-id pulsemixer --change-volume -5
  - keybinding:
    name: darker
    key: XF86AudioMute
    exec: --no-startup-id pulsemixer --toggle-mute 
  - keybinding:
    name: darker
    key: XF86MonBrightnessDown
    exec: --no-startup-id light -U 12
  - keybinding:
    name: lighter
    key: XF86MonBrightnessUp
    exec: --no-startup-id light -A 9


i3_applications:
  - application:
    class: "Firefox"
    name: "firefox"
    workspace: 2
    on_startup: true
  - application:
    class: "Thunderbird"
    name: "thunderbird"
    workspace: 9
    on_startup: true

i3_run_on_startup:
  - nextcloud
  - nm-applet


i3:
  font_size: 11
  focus_follows_mouse: true

i3_desktop_env:
  background: "/home/{{ user }}/.config/background.png"

i3lock_options: "i3lock --image=/home/{{ user }}/.config/lockscreen.png"


# Firefox config
username: "{{ user }}"

search_engines:
  - google
  - duckduckgo
  - invidious
  - searx
  - qwant

addon_list:
  - name: passff
    directory: "passff@invicem.pro.xpi"    

  - name: ublock-origin
    directory: "uBlock0@raymondhill.net"

  - name: umatrix
    directory: "uMatrix@raymondhill.net"

  - name: decentraleyes
    directory: "jid1-BoFifL9Vbdl2zQ@jetpack"

  - name: first-party-isolation
    directory: "{33c93ccc-ceed-47d2-9645-805ea58c8a07}"

  - name: neat-url
    directory: "neaturl@hugsmile.eu"

  - name: skip-redirect
    directory: "skipredirect@sblask"

  - name: temporary-containers
    directory: "{c607c8df-14a7-4f28-894f-29e8722976af}"

  - name: multi-account-containers
    directory: "@testpilot-containers"


